require("__proceduralsystems__.prototypes.entities")
require("__proceduralsystems__.prototypes.fluid")
require("__proceduralsystems__.prototypes.item")
require("__proceduralsystems__.prototypes.item-groups")
require("__proceduralsystems__.prototypes.fuel-category")
require("__proceduralsystems__.prototypes.recipe-category")
require("__proceduralsystems__.prototypes.entity.resources")
require("__proceduralsystems__.prototypes.autoplace-controls")

require("__proceduralsystems__.prototypes.recipe")
require("__proceduralsystems__.prototypes.particles")
require("__proceduralsystems__.prototypes.explosions")
require("__proceduralsystems__.prototypes.particle-animations")
require("__proceduralsystems__.prototypes.asteroid")
