require("__procedural-systems__.prototypes.entities")
require("__procedural-systems__.prototypes.fluid")
require("__procedural-systems__.prototypes.item")
require("__procedural-systems__.prototypes.item-groups")
require("__procedural-systems__.prototypes.fuel-category")
require("__procedural-systems__.prototypes.recipe-category")
require("__procedural-systems__.prototypes.entity.resources")
require("__procedural-systems__.prototypes.autoplace-controls")

require("__procedural-systems__.prototypes.recipe")
require("__procedural-systems__.prototypes.procedural-recipe")
require("__procedural-systems__.prototypes.particles")
require("__procedural-systems__.prototypes.explosions")
require("__procedural-systems__.prototypes.particle-animations")
require("__procedural-systems__.prototypes.asteroid")
require("__procedural-systems__.prototypes.planet.asteroid-spawn-definitions")
